# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "2.6"
  - "2.7"
# pylint 1.4 does not run under python 2.6
install:
 - pip install pyOpenSSL
 - pip install pylint
 - pip install pyflakes
 - pip install pep8
script:
  - pep8 back bin/back
  - python --version 2>&1 | grep 2\.6\.. || pylint --rcfile=pylintrc back bin/back
  - pyflakes back bin/back
  - nosetests back
